### ISSUE TITLE
Docker更新问题

### ISSUE THREAD

**Issue by anakinlee99** [wuzhi01/MyActions#10]
请问大佬，Gitee库无法访问了，现在Docker是不是就无法更新了？
以后还会恢复吗？还是说Docker以后就无法使用了？
请解答一下，谢谢！

**Comment by wuzhi01** [comment]
会恢复避避风头，不用设置我如果公开库之后自然就可以更新了

**Comment by anakinlee99** [comment]
OK  感谢答复，坐等。
