### ISSUE TITLE
怎么扫码获取ck？

### ISSUE THREAD

**Issue by alabelleetoile** [wuzhi01/MyActions#12]
扫码获取京东cookie，此方式得到的cookie有效期为90天(实际待测试)

如扫描不到，请使用工具(例如在线二维码工具：https://cli.im)手动生成如下url二维

运行node getJDCookie.js后二维码扫不出来

**Comment by wuzhi01** [comment]
部署docker容器之后去控制面板扫码，其余环境自行解决
