### ISSUE TITLE
push plus推送接口变更

### ISSUE THREAD

**Issue by NittaAkio** [wuzhi01/MyActions#14]
scripts/sendNotify.js中push plus调用的接口会出现“用户状态不合法”无法推送，需改用http://pushplus.hxtrip.com/send

**Comment by NittaAkio** [comment]
补充：我是在使用一多推推送功能时发现这个问题，一对一是否这样没有测试

**Comment by wuzhi01** [comment]
http://www.pushplus.plus/去这里更换token，原pushplus之前有公告称四月份会停止运营
