### ISSUE TITLE
全民抢红包失效了

### ISSUE THREAD

**Issue by belleetoile** [wuzhi01/MyActions#15]
任务     状态  红包是否领取
券”逛10s   0/10      否
领3张优惠券   0/3      否
4个精选活动   0/4      否
览签到领现金   0/1      否
6个精选频道   0/6      否
[京东首页点击“领券”逛10s] 任务未开发
[去领券中心领3张优惠券] 任务未开发
开始做浏览任务

都不能领取了

开始做浏览任务

开始做浏览任务

京东全民开红包获得红包：0元

**Comment by wuzhi01** [comment]
已经同步最新的
