### ISSUE TITLE
我是我，你是你

### ISSUE THREAD

**Issue by luoli8** [wuzhi01/MyActions#20]
我是我，你是你，若要辨真伪只请西天如来和谛听，你们多牛逼！（还挺顺嘴）

我一没说过代表你，二一个你又没做过，何必着急先害怕，何必又急于跟小学生澄清而伤害帮你的人？
别人帮了你你骂也骂了，你倒好，拿着刀子都解不了你的急。

提问者一没说自己的脚本，二更没必要兴师问罪，说一声删了便是，你怼人我便怼怼你，我也只是以为我的名义怼怼他而已
提问者大可与我来斯，没想到作者听了小学生言论先来撕帮你的我，可笑可笑，原来狗是我，嘿嘿(●ˇ∀ˇ●)

整急眼的作者什么都干出来啊。

可见小学生是谁？
又可见shuye你的人品又在哪？我看你才是为了小学生而小学生的行为吧！

**Comment by wuzhi01** [comment]
那叫帮我吗？你可不知道现在满世界的人私信我怎么骂我呢，我急着扩散？我怎么急着扩散了，现在所有人都以为你这个是我自己的小号然后矛头再次全部指向我，你现在可没被私信各种污言秽语骂过。我很久前就发过这种骂来骂去没有任何意思

**Comment by wuzhi01** [comment]
你自认为你是你我是我，但是他们不这么认为，本来大家相安无事，非要搞这一出搞的双方都不高兴，然后我就成了那个恶人了？，对了编辑有记录的想说什么直接回复就是了。没必要刻意更改说辞

**Comment by luoli8** [comment]
> 你自认为你是你我是我，但是他们不这么认为，本来大家相安无事，非要搞这一出搞的双方都不高兴，然后我就成了那个恶人了？，对了编辑有记录的想说什么直接回复就是了。没必要刻意更改说辞

我不改我怕你们听不懂什么叫人话！

**Comment by wuzhi01** [comment]
> > 你自认为你是你我是我，但是他们不这么认为，本来大家相安无事，非要搞这一出搞的双方都不高兴，然后我就成了那个恶人了？，对了编辑有记录的想说什么直接回复就是了。没必要刻意更改说辞
> 
> 我不改我怕你们听不懂什么叫人话！

我也没空跟你在这扯，只是你这种怼人的行为影响到我了。你怎么想是你的事情你认为我着急也好害怕也罢。已经没有继续讨论下去的意义 我的issue不允许有辱骂 另外一个库也早已封禁，因为有人因为你的言论对我有误解并且人身攻击我影响到了我的正常生活，而我发个公告而已就这么简单。

**Comment by wuzhi01** [comment]
> 我是我，你是你，若要辨真伪只请西天如来和谛听，你们多牛逼！（还挺顺嘴）
> 
> 我一没说过代表你，二一个你又没做过，何必着急先害怕，何必又急于跟小学生澄清而伤害帮你的人？
> 别人帮了你你骂也骂了，你倒好，拿着刀子都解不了你的急。
> 
> 提问者一没说自己的脚本，二更没必要兴师问罪，说一声删了便是，你怼人我便怼怼你，我也只是以为我的名义怼怼他而已
> 提问者大可与我来斯，没想到作者听了小学生言论先来撕帮你的我，可笑可笑，原来狗是我，嘿嘿(●ˇ∀ˇ●)
> 
> 整急眼的作者什么都干出来啊。
> 
> 可见小学生是谁？
> 又可见shuye你的人品又在哪？我看你才是为了小学生而小学生的行为吧！

另外，当真谈人品？

**Comment by luoli8** [comment]
> > 我是我，你是你，若要辨真伪只请西天如来和谛听，你们多牛逼！（还挺顺嘴）
> > 我一没说过代表你，二一个你又没做过，何必着急先害怕，何必又急于跟小学生澄清而伤害帮你的人？
> > 别人帮了你你骂也骂了，你倒好，拿着刀子都解不了你的急。
> > 提问者一没说自己的脚本，二更没必要兴师问罪，说一声删了便是，你怼人我便怼怼你，我也只是以为我的名义怼怼他而已
> > 提问者大可与我来斯，没想到作者听了小学生言论先来撕帮你的我，可笑可笑，原来狗是我，嘿嘿(●ˇ∀ˇ●)
> > 整急眼的作者什么都干出来啊。
> > 可见小学生是谁？
> > 又可见shuye你的人品又在哪？我看你才是为了小学生而小学生的行为吧！
> 
> 另外，当真谈人品？

算我自己认栽shuye行了吧？的确没要求谈了

**Comment by wuzhi01** [comment]
> > > 我是我，你是你，若要辨真伪只请西天如来和谛听，你们多牛逼！（还挺顺嘴）
> > > 我一没说过代表你，二一个你又没做过，何必着急先害怕，何必又急于跟小学生澄清而伤害帮你的人？
> > > 别人帮了你你骂也骂了，你倒好，拿着刀子都解不了你的急。
> > > 提问者一没说自己的脚本，二更没必要兴师问罪，说一声删了便是，你怼人我便怼怼你，我也只是以为我的名义怼怼他而已
> > > 提问者大可与我来斯，没想到作者听了小学生言论先来撕帮你的我，可笑可笑，原来狗是我，嘿嘿(●ˇ∀ˇ●)
> > > 整急眼的作者什么都干出来啊。
> > > 可见小学生是谁？
> > > 又可见shuye你的人品又在哪？我看你才是为了小学生而小学生的行为吧！
> > 
> > 
> > 另外，当真谈人品？
> 
> 算我自己认栽shuye行了吧？的确没要求谈了

这个世界的运行规律就是如此，不论你是初心如何，但是你就要对你自己做出的行为以及对此行为产生的后果负责，何来认栽一说。
