### ISSUE TITLE
DOCKER安装完成后，正常运行，第二天访问IP:5678出现故障

### ISSUE THREAD

**Issue by cisco6005** [wuzhi01/MyActions#29]
语法错误：Object.module.exports
    处的意外标识符[解析时]（/jd/panel/node_modules/qs/lib/ parse.js :224 :19）位于parseExtendedQueryString（/ jd / panel / node_modules / express / lib / utils。 js：292：13）
    在Layer.handle处查询（/jd/panel/node_modules/express/lib/middleware/query.js:42:19）
    [作为handle_request]（/ jd / panel / node_modules / express / lib /
    在trim_prefix（/jd/panel/node_modules/express/lib/router/index.js:317:13）
    中的router / layer.js：95：5）在/ jd / panel / node_modules / express / lib / router / index中。
    在Function.process_params（/jd/panel/node_modules/express/lib/router/index.js:335:12）
    处的js：284：7在下一个（/jd/panel/node_modules/express/lib/router/index.js处的js：284：7 ：275：10）
    在Function.handle（/jd/panel/node_modules/express/lib/router/index.js:174:3）
    在Function.handle（/jd/panel/node_modules/express/lib/application.js:174:10）

**Comment by wuzhi01** [comment]
重启 或者重新部署
