### ISSUE TITLE
docker下更新错误，请帮忙看看

### ISSUE THREAD

**Issue by cisco6005** [wuzhi01/MyActions#3]
系统时间：2021-03-20 16:02:09

JS脚本目录：/jd/scripts

--------------------------------------------------------------

更新shell...

Fetching origin
HEAD is now at 34a56a8 Update export_sharecodes.sh

更新shell成功...

更新scripts...

fatal: unknown index entry format 0x61720000
fatal: unknown index entry format 0x61720000

更新scripts失败，请检查原因...

**Comment by cisco6005** [comment]
我在路由器根目录建立了JD文件，然后用docker run -dit \
	-v /JD/jd/config:/jd/config \
	-v /JD/jd/log:/jd/log \
	-v /JD/jd/scripts:/jd/scripts  \
        --network host \
        -e ENABLE_HANGUP=true \
        -e ENABLE_WEB_PANEL=true \
	--name jd \
	--hostname jd \
	--restart always \
	shuye72/jd-base:gitee
命令拉取的源码，是不是脚本路径出现错误？

**Comment by shuyeshuye** [comment]
看起来没错，路由器我不太清楚，删除容器重拉试试
